/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createPaginatedRecipesResponseFromDiscriminatorValue, createRecipeResponseFromDiscriminatorValue, serializeCreateRecipeRequest, serializeRecipeResponse, type CreateRecipeRequest, type HttpValidationProblemDetails, type PaginatedRecipesResponse, type RecipeResponse } from '../../models/index.js';
// @ts-ignore
import { RecipesItemRequestBuilderNavigationMetadata, RecipesItemRequestBuilderRequestsMetadata, type RecipesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { PublishedRequestBuilderRequestsMetadata, type PublishedRequestBuilder } from './published/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes
 */
export interface RecipesRequestBuilder extends BaseRequestBuilder<RecipesRequestBuilder> {
    /**
     * The published property
     */
    get published(): PublishedRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.recipes.item collection
     * @param id Unique identifier of the item
     * @returns {RecipesItemRequestBuilder}
     */
     byId(id: Guid) : RecipesItemRequestBuilder;
    /**
     * Get a list of recipes with filtering, searching, and pagination
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaginatedRecipesResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<RecipesRequestBuilderGetQueryParameters> | undefined) : Promise<PaginatedRecipesResponse | undefined>;
    /**
     * Create a new recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeResponse | undefined>;
    /**
     * Get a list of recipes with filtering, searching, and pagination
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RecipesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a new recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a list of recipes with filtering, searching, and pagination
 */
export interface RecipesRequestBuilderGetQueryParameters {
    categories?: string;
    creatorId?: Guid;
    difficulty?: string;
    page?: string;
    pageSize?: string;
    prepTime?: string;
    search?: string;
    sortBy?: string;
    sortOrder?: string;
    status?: string;
}
/**
 * Uri template for the request builder.
 */
export const RecipesRequestBuilderUriTemplate = "{+baseurl}/api/recipes{?categories*,creatorId*,difficulty*,page*,pageSize*,prepTime*,search*,sortBy*,sortOrder*,status*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecipesRequestBuilderNavigationMetadata: Record<Exclude<keyof RecipesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: RecipesItemRequestBuilderRequestsMetadata,
        navigationMetadata: RecipesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    published: {
        requestsMetadata: PublishedRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecipesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RecipesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPaginatedRecipesResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: RecipesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateRecipeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
