/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRatingResponseFromDiscriminatorValue, serializeRateRecipeRequest, serializeRatingResponse, type RateRecipeRequest, type RatingResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}/rate
 */
export interface RateRequestBuilder extends BaseRequestBuilder<RateRequestBuilder> {
    /**
     * Remove a user's rating from a recipe.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Rate a recipe (1-5 stars). Updates rating if already rated.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RatingResponse>}
     */
     post(body: RateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RatingResponse | undefined>;
    /**
     * Remove a user's rating from a recipe.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Rate a recipe (1-5 stars). Updates rating if already rated.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RateRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}/rate";
/**
 * Metadata for all the requests in the request builder.
 */
export const RateRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RateRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    post: {
        uriTemplate: RateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRatingResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRateRecipeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
