/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAchievementResponseFromDiscriminatorValue, type AchievementResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/achievements
 */
export interface AchievementsRequestBuilder extends BaseRequestBuilder<AchievementsRequestBuilder> {
    /**
     * Get the unlocked achievements of the currently authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AchievementResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AchievementResponse[] | undefined>;
    /**
     * Get the unlocked achievements of the currently authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AchievementsRequestBuilderUriTemplate = "{+baseurl}/api/user/achievements";
/**
 * Metadata for all the requests in the request builder.
 */
export const AchievementsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AchievementsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createAchievementResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
