/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DishesRequestBuilderNavigationMetadata, DishesRequestBuilderRequestsMetadata, type DishesRequestBuilder } from './dishes/index.js';
// @ts-ignore
import { IngredientsRequestBuilderNavigationMetadata, IngredientsRequestBuilderRequestsMetadata, type IngredientsRequestBuilder } from './ingredients/index.js';
// @ts-ignore
import { type WeatherforecastRequestBuilder, WeatherforecastRequestBuilderRequestsMetadata } from './weatherforecast/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The dishes property
     */
    get dishes(): DishesRequestBuilder;
    /**
     * The ingredients property
     */
    get ingredients(): IngredientsRequestBuilder;
    /**
     * The weatherforecast property
     */
    get weatherforecast(): WeatherforecastRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    dishes: {
        requestsMetadata: DishesRequestBuilderRequestsMetadata,
        navigationMetadata: DishesRequestBuilderNavigationMetadata,
    },
    ingredients: {
        requestsMetadata: IngredientsRequestBuilderRequestsMetadata,
        navigationMetadata: IngredientsRequestBuilderNavigationMetadata,
    },
    weatherforecast: {
        requestsMetadata: WeatherforecastRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
