/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountRequestBuilderNavigationMetadata, type AccountRequestBuilder } from './account/index.js';
// @ts-ignore
import { DishesRequestBuilderNavigationMetadata, DishesRequestBuilderRequestsMetadata, type DishesRequestBuilder } from './dishes/index.js';
// @ts-ignore
import { IngredientsRequestBuilderNavigationMetadata, IngredientsRequestBuilderRequestsMetadata, type IngredientsRequestBuilder } from './ingredients/index.js';
// @ts-ignore
import { RecipesRequestBuilderNavigationMetadata, RecipesRequestBuilderRequestsMetadata, type RecipesRequestBuilder } from './recipes/index.js';
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata } from './user/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The account property
     */
    get account(): AccountRequestBuilder;
    /**
     * The dishes property
     */
    get dishes(): DishesRequestBuilder;
    /**
     * The ingredients property
     */
    get ingredients(): IngredientsRequestBuilder;
    /**
     * The recipes property
     */
    get recipes(): RecipesRequestBuilder;
    /**
     * The user property
     */
    get user(): UserRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    account: {
        navigationMetadata: AccountRequestBuilderNavigationMetadata,
    },
    dishes: {
        requestsMetadata: DishesRequestBuilderRequestsMetadata,
        navigationMetadata: DishesRequestBuilderNavigationMetadata,
    },
    ingredients: {
        requestsMetadata: IngredientsRequestBuilderRequestsMetadata,
        navigationMetadata: IngredientsRequestBuilderNavigationMetadata,
    },
    recipes: {
        requestsMetadata: RecipesRequestBuilderRequestsMetadata,
        navigationMetadata: RecipesRequestBuilderNavigationMetadata,
    },
    user: {
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
