/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUserStatisticsResponseFromDiscriminatorValue, type UserStatisticsResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/statistics
 */
export interface StatisticsRequestBuilder extends BaseRequestBuilder<StatisticsRequestBuilder> {
    /**
     * Get the currently authenticated user's creator statistics.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserStatisticsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserStatisticsResponse | undefined>;
    /**
     * Get the currently authenticated user's creator statistics.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatisticsRequestBuilderUriTemplate = "{+baseurl}/api/user/statistics";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatisticsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatisticsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createUserStatisticsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
