// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dishes.Server.Data;

#nullable disable

namespace dishes.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.Property<Guid>("DishesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("TEXT");

                    b.HasKey("DishesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("DishIngredient", (string)null);

                    b.HasData(
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("c19099ed-94db-44ba-885b-0ad7205d5e40")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("0c4dc798-b38b-4a1c-905c-a9e76dbef17b")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("937b1ba1-7969-4324-9ab5-afb0e4d875e6")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("7a2fbc72-bb33-49de-bd23-c78fceb367fc")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("b5f336e2-c226-4389-aac3-2499325a3de9")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe")
                        },
                        new
                        {
                            DishesId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            IngredientsId = new Guid("d5cad9a4-144e-4a3d-858d-9840792fa65d")
                        },
                        new
                        {
                            DishesId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            IngredientsId = new Guid("aab31c70-57ce-4b6d-a66c-9c1b094e915d")
                        },
                        new
                        {
                            DishesId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            IngredientsId = new Guid("fef8b722-664d-403f-ae3c-05f8ed7d7a1f")
                        },
                        new
                        {
                            DishesId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            IngredientsId = new Guid("8d5a1b40-6677-4545-b6e8-5ba93efda0a1")
                        },
                        new
                        {
                            DishesId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            IngredientsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe")
                        },
                        new
                        {
                            DishesId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            IngredientsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("40563e5b-e538-4084-9587-3df74fae21d4")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("f350e1a0-38de-42fe-ada5-ae436378ee5b")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("d5cad9a4-144e-4a3d-858d-9840792fa65d")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("fef8b722-664d-403f-ae3c-05f8ed7d7a1f")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("b617df23-3d91-40e1-99aa-b07d264aa937")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("b8b9a6ae-9bcc-4fb3-b883-5974e04eda56")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("ecd396c3-4403-4fbf-83ca-94a8e9d859b3")
                        },
                        new
                        {
                            DishesId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            IngredientsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("c2c75b40-2453-416e-a7ed-3505b121d671")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("b8b9a6ae-9bcc-4fb3-b883-5974e04eda56")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("3bd3f0a1-87d3-4b85-94fa-ba92bd1874e7")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("047ab5cc-d041-486e-9d22-a0860fb13237")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("e0017fe1-773f-4a59-9730-9489833c6e8e")
                        },
                        new
                        {
                            DishesId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            IngredientsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("c9b46f9c-d6ce-42c3-8736-2cddbbadee10")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("a07cde83-3127-45da-bbd5-04a7c8d13aa4")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("ebe94d5d-2ad8-4886-b246-05a1fad83d1c")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("40563e5b-e538-4084-9587-3df74fae21d4")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("c2c75b40-2453-416e-a7ed-3505b121d671")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("d5cad9a4-144e-4a3d-858d-9840792fa65d")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("047ab5cc-d041-486e-9d22-a0860fb13237")
                        },
                        new
                        {
                            DishesId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            IngredientsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.AppIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CulinaryTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Badges", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dishes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            Name = "Flemish Beef stew with chicory"
                        },
                        new
                        {
                            Id = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            Name = "Mussels with french fries"
                        },
                        new
                        {
                            Id = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            Name = "Ragu alla bolognaise"
                        },
                        new
                        {
                            Id = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            Name = "Rendang"
                        },
                        new
                        {
                            Id = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            Name = "Fish Masala"
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Onion"
                        },
                        new
                        {
                            Id = new Guid("c19099ed-94db-44ba-885b-0ad7205d5e40"),
                            Name = "Dark beer"
                        },
                        new
                        {
                            Id = new Guid("0c4dc798-b38b-4a1c-905c-a9e76dbef17b"),
                            Name = "Brown piece of bread"
                        },
                        new
                        {
                            Id = new Guid("937b1ba1-7969-4324-9ab5-afb0e4d875e6"),
                            Name = "Mustard"
                        },
                        new
                        {
                            Id = new Guid("7a2fbc72-bb33-49de-bd23-c78fceb367fc"),
                            Name = "Chicory"
                        },
                        new
                        {
                            Id = new Guid("b5f336e2-c226-4389-aac3-2499325a3de9"),
                            Name = "Mayo"
                        },
                        new
                        {
                            Id = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            Name = "Various spices"
                        },
                        new
                        {
                            Id = new Guid("aab31c70-57ce-4b6d-a66c-9c1b094e915d"),
                            Name = "Mussels"
                        },
                        new
                        {
                            Id = new Guid("fef8b722-664d-403f-ae3c-05f8ed7d7a1f"),
                            Name = "Celery"
                        },
                        new
                        {
                            Id = new Guid("8d5a1b40-6677-4545-b6e8-5ba93efda0a1"),
                            Name = "French fries"
                        },
                        new
                        {
                            Id = new Guid("40563e5b-e538-4084-9587-3df74fae21d4"),
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = new Guid("f350e1a0-38de-42fe-ada5-ae436378ee5b"),
                            Name = "Tomato paste"
                        },
                        new
                        {
                            Id = new Guid("d5cad9a4-144e-4a3d-858d-9840792fa65d"),
                            Name = "Bay leave"
                        },
                        new
                        {
                            Id = new Guid("b617df23-3d91-40e1-99aa-b07d264aa937"),
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("b8b9a6ae-9bcc-4fb3-b883-5974e04eda56"),
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("ecd396c3-4403-4fbf-83ca-94a8e9d859b3"),
                            Name = "Red wine"
                        },
                        new
                        {
                            Id = new Guid("c2c75b40-2453-416e-a7ed-3505b121d671"),
                            Name = "Coconut milk"
                        },
                        new
                        {
                            Id = new Guid("3bd3f0a1-87d3-4b85-94fa-ba92bd1874e7"),
                            Name = "Ginger"
                        },
                        new
                        {
                            Id = new Guid("047ab5cc-d041-486e-9d22-a0860fb13237"),
                            Name = "Chili pepper"
                        },
                        new
                        {
                            Id = new Guid("e0017fe1-773f-4a59-9730-9489833c6e8e"),
                            Name = "Tamarind paste"
                        },
                        new
                        {
                            Id = new Guid("c9b46f9c-d6ce-42c3-8736-2cddbbadee10"),
                            Name = "Firm fish"
                        },
                        new
                        {
                            Id = new Guid("a07cde83-3127-45da-bbd5-04a7c8d13aa4"),
                            Name = "Ginger garlic paste"
                        },
                        new
                        {
                            Id = new Guid("ebe94d5d-2ad8-4886-b246-05a1fad83d1c"),
                            Name = "Garam masala"
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            CoverPhotoPath = "/images/carbonara.jpg",
                            CreatedAt = new DateTime(2024, 11, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("aa1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5c"),
                            Description = "Classic Italian pasta with eggs, cheese, and bacon",
                            Difficulty = "Easy",
                            PrepTime = "30 mins",
                            Status = 0,
                            Title = "Spaghetti Carbonara",
                            UpdatedAt = new DateTime(2024, 11, 15, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bf2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            CoverPhotoPath = "/images/beefstew.jpg",
                            CreatedAt = new DateTime(2024, 11, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("aa1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5c"),
                            Description = "Hearty beef stew with vegetables and rich gravy",
                            Difficulty = "Medium",
                            PrepTime = "2 hours",
                            Status = 0,
                            Title = "Beef Stew",
                            UpdatedAt = new DateTime(2024, 11, 25, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b0d8b33-cdf8-47d6-b3a1-8d5f1e9a2c3b"),
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = new Guid("7c1e9c44-def9-48e7-c4b2-9e6f2f0b3d4c"),
                            Name = "Appetizer"
                        },
                        new
                        {
                            Id = new Guid("8d2f0d55-efa0-49f8-d5c3-af7b3a1c4e5d"),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = new Guid("9e3a1e66-fab1-40a9-e6d4-ba8b4b2d5f6e"),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("af4a2f77-abc2-41b0-f7e5-cb9c5c3e6a7f"),
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = new Guid("ba5b3a88-bcd3-42c1-a8f6-dc0d6c4f7b8a"),
                            Name = "Baking"
                        },
                        new
                        {
                            Id = new Guid("cb6c4b99-cde4-43d2-b9a7-ed1e7d5a8c9b"),
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("dc7d5c00-def5-44e3-caa8-fe2f8e6b9d0c"),
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("ed8e6d11-efa6-45f4-dbc9-af3a9f7c0e1d"),
                            Name = "Snack"
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            IngredientName = "Spaghetti",
                            Quantity = 400m,
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("db4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            IngredientName = "Eggs",
                            Quantity = 4m,
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Unit = "whole"
                        },
                        new
                        {
                            Id = new Guid("ec5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
                            IngredientName = "Parmesan Cheese",
                            Quantity = 200m,
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("fd6a7b8c-9d0e-1f2a-3b4c-5d6e7f8a9b0c"),
                            IngredientName = "Bacon",
                            Quantity = 150m,
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeInstructions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0c1d"),
                            Description = "Cook spaghetti in salted boiling water until al dente",
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("bf8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e"),
                            Description = "Cook bacon until crispy and chop into pieces",
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("ca9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f"),
                            Description = "Mix eggs and grated cheese in a bowl",
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            StepNumber = 3
                        },
                        new
                        {
                            Id = new Guid("db0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
                            Description = "Drain pasta and mix with bacon, then toss with egg mixture off heat",
                            RecipeId = new Guid("af1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            StepNumber = 4
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeRecipeCategory", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecipeRecipeCategory", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeRecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeRecipeTag", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecipeTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa9f7e22-fbb7-46e5-ead0-bf3a0a5f1e2f"),
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = new Guid("ab0a8f33-acc8-47f6-fbe1-ca4b1b6a2f3a"),
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = new Guid("bc1b9a44-bdd9-48a7-acb2-db5c2c7b3a4b"),
                            Name = "Gluten-Free"
                        },
                        new
                        {
                            Id = new Guid("cd2c0b55-ceea-49b8-bdc3-ec6d3d8c4b5c"),
                            Name = "Quick"
                        },
                        new
                        {
                            Id = new Guid("de3d1c66-dffb-40c9-ceb4-fd7e4e9d5c6d"),
                            Name = "Comfort Food"
                        });
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowedUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FollowedUserId");

                    b.HasIndex("FollowerUserId", "FollowedUserId")
                        .IsUnique();

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserRecipeFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("UserRecipeFavorites", (string)null);
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserRecipeRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("UserRecipeRatings", (string)null);
                });

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeInstruction", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeRecipeCategory", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.RecipeCategory", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Categories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeRecipeTag", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.RecipeTag", "Tag")
                        .WithMany("Recipes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserAchievement", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserBadge", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserFollow", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", "Followed")
                        .WithMany()
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dishes.Server.Data.Entities.AppIdentityUser", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserRecipeFavorite", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.UserRecipeRating", b =>
                {
                    b.HasOne("dishes.Server.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Favorites");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeCategory", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("dishes.Server.Data.Entities.RecipeTag", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
