/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type DateOnly, type Guid, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Dish}
 */
// @ts-ignore
export function createDishFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDish;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Ingredient}
 */
// @ts-ignore
export function createIngredientFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIngredient;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WeatherForecast}
 */
// @ts-ignore
export function createWeatherForecastFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWeatherForecast;
}
/**
 * The deserialization information for the current model
 * @param Dish The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDish(dish: Partial<Dish> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { dish.id = n.getGuidValue(); },
        "ingredients": n => { dish.ingredients = n.getCollectionOfObjectValues<Ingredient>(createIngredientFromDiscriminatorValue); },
        "name": n => { dish.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Ingredient The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIngredient(ingredient: Partial<Ingredient> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "dishes": n => { ingredient.dishes = n.getCollectionOfObjectValues<Dish>(createDishFromDiscriminatorValue); },
        "id": n => { ingredient.id = n.getGuidValue(); },
        "name": n => { ingredient.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WeatherForecast The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWeatherForecast(weatherForecast: Partial<WeatherForecast> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "date": n => { weatherForecast.date = n.getDateOnlyValue(); },
        "summary": n => { weatherForecast.summary = n.getStringValue(); },
        "temperatureC": n => { weatherForecast.temperatureC = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "temperatureF": n => { weatherForecast.temperatureF = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
export interface Dish extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The ingredients property
     */
    ingredients?: Ingredient[] | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface Ingredient extends AdditionalDataHolder, Parsable {
    /**
     * The dishes property
     */
    dishes?: Dish[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Serializes information the current object
 * @param Dish The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDish(writer: SerializationWriter, dish: Partial<Dish> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dish || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", dish.id);
    writer.writeCollectionOfObjectValues<Ingredient>("ingredients", dish.ingredients, serializeIngredient);
    writer.writeStringValue("name", dish.name);
    writer.writeAdditionalData(dish.additionalData);
}
/**
 * Serializes information the current object
 * @param Ingredient The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIngredient(writer: SerializationWriter, ingredient: Partial<Ingredient> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!ingredient || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Dish>("dishes", ingredient.dishes, serializeDish);
    writer.writeGuidValue("id", ingredient.id);
    writer.writeStringValue("name", ingredient.name);
    writer.writeAdditionalData(ingredient.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WeatherForecast The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWeatherForecast(writer: SerializationWriter, weatherForecast: Partial<WeatherForecast> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!weatherForecast || isSerializingDerivedType) { return; }
    writer.writeDateOnlyValue("date", weatherForecast.date);
    writer.writeStringValue("summary", weatherForecast.summary);
    writer.writeObjectValue("temperatureC", weatherForecast.temperatureC);
    writer.writeObjectValue("temperatureF", weatherForecast.temperatureF);
    writer.writeAdditionalData(weatherForecast.additionalData);
}
export interface WeatherForecast extends AdditionalDataHolder, Parsable {
    /**
     * The date property
     */
    date?: DateOnly | null;
    /**
     * The summary property
     */
    summary?: string | null;
    /**
     * The temperatureC property
     */
    temperatureC?: UntypedNode | null;
    /**
     * The temperatureF property
     */
    temperatureF?: UntypedNode | null;
}
/* tslint:enable */
/* eslint-enable */
