/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDishFromDiscriminatorValue, createDishResponseFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, serializeDish, serializeDishRequest, type Dish, type DishRequest, type DishResponse, type HttpValidationProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/dishes/{id}
 */
export interface DishesItemRequestBuilder extends BaseRequestBuilder<DishesItemRequestBuilder> {
    /**
     * Delete an existing dish
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get a dish by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DishResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DishResponse | undefined>;
    /**
     * Update an existing dish
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Dish>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: DishRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Dish | undefined>;
    /**
     * Delete an existing dish
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get a dish by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update an existing dish
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: DishRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DishesItemRequestBuilderUriTemplate = "{+baseurl}/api/dishes/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DishesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: DishesItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: DishesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createDishResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: DishesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDishFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDishRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
