/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDishFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, serializeDish, serializeDishRequest, type Dish, type DishRequest, type HttpValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { DishesItemRequestBuilderRequestsMetadata, type DishesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/dishes
 */
export interface DishesRequestBuilder extends BaseRequestBuilder<DishesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.dishes.item collection
     * @param id Unique identifier of the item
     * @returns {DishesItemRequestBuilder}
     */
     byId(id: Guid) : DishesItemRequestBuilder;
    /**
     * Get all dishes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Dish[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Dish[] | undefined>;
    /**
     * Create a new dish
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Dish>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: DishRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Dish | undefined>;
    /**
     * Get all dishes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new dish
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DishRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DishesRequestBuilderUriTemplate = "{+baseurl}/api/dishes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DishesRequestBuilderNavigationMetadata: Record<Exclude<keyof DishesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: DishesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DishesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DishesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDishFromDiscriminatorValue,
    },
    post: {
        uriTemplate: DishesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDishFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDishRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
