/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BadgesRequestBuilderRequestsMetadata, type BadgesRequestBuilder } from './badges/index.js';
// @ts-ignore
import { ConfirmEmailRequestBuilderRequestsMetadata, type ConfirmEmailRequestBuilder } from './confirmEmail/index.js';
// @ts-ignore
import { ForgotPasswordRequestBuilderRequestsMetadata, type ForgotPasswordRequestBuilder } from './forgotPassword/index.js';
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { ManageRequestBuilderNavigationMetadata, type ManageRequestBuilder } from './manage/index.js';
// @ts-ignore
import { ProfileRequestBuilderRequestsMetadata, type ProfileRequestBuilder } from './profile/index.js';
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { RegisterRequestBuilderRequestsMetadata, type RegisterRequestBuilder } from './register/index.js';
// @ts-ignore
import { ResendConfirmationEmailRequestBuilderRequestsMetadata, type ResendConfirmationEmailRequestBuilder } from './resendConfirmationEmail/index.js';
// @ts-ignore
import { ResetPasswordRequestBuilderRequestsMetadata, type ResetPasswordRequestBuilder } from './resetPassword/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user
 */
export interface UserRequestBuilder extends BaseRequestBuilder<UserRequestBuilder> {
    /**
     * The badges property
     */
    get badges(): BadgesRequestBuilder;
    /**
     * The confirmEmail property
     */
    get confirmEmail(): ConfirmEmailRequestBuilder;
    /**
     * The forgotPassword property
     */
    get forgotPassword(): ForgotPasswordRequestBuilder;
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The manage property
     */
    get manage(): ManageRequestBuilder;
    /**
     * The profile property
     */
    get profile(): ProfileRequestBuilder;
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
    /**
     * The register property
     */
    get register(): RegisterRequestBuilder;
    /**
     * The resendConfirmationEmail property
     */
    get resendConfirmationEmail(): ResendConfirmationEmailRequestBuilder;
    /**
     * The resetPassword property
     */
    get resetPassword(): ResetPasswordRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UserRequestBuilderUriTemplate = "{+baseurl}/api/user";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UserRequestBuilderNavigationMetadata: Record<Exclude<keyof UserRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    badges: {
        requestsMetadata: BadgesRequestBuilderRequestsMetadata,
    },
    confirmEmail: {
        requestsMetadata: ConfirmEmailRequestBuilderRequestsMetadata,
    },
    forgotPassword: {
        requestsMetadata: ForgotPasswordRequestBuilderRequestsMetadata,
    },
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    manage: {
        navigationMetadata: ManageRequestBuilderNavigationMetadata,
    },
    profile: {
        requestsMetadata: ProfileRequestBuilderRequestsMetadata,
    },
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
    register: {
        requestsMetadata: RegisterRequestBuilderRequestsMetadata,
    },
    resendConfirmationEmail: {
        requestsMetadata: ResendConfirmationEmailRequestBuilderRequestsMetadata,
    },
    resetPassword: {
        requestsMetadata: ResetPasswordRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
