/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFavoriteResponseFromDiscriminatorValue, type FavoriteResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}/favorite
 */
export interface FavoriteRequestBuilder extends BaseRequestBuilder<FavoriteRequestBuilder> {
    /**
     * Remove a recipe from user's favorites.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Add a recipe to user's favorites.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FavoriteResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FavoriteResponse | undefined>;
    /**
     * Remove a recipe from user's favorites.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Add a recipe to user's favorites.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FavoriteRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}/favorite";
/**
 * Metadata for all the requests in the request builder.
 */
export const FavoriteRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: FavoriteRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    post: {
        uriTemplate: FavoriteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFavoriteResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
