/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createIngredientFromDiscriminatorValue, serializeIngredient, serializeIngredientRequest, type HttpValidationProblemDetails, type Ingredient, type IngredientRequest } from '../../models/index.js';
// @ts-ignore
import { IngredientsItemRequestBuilderRequestsMetadata, type IngredientsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ingredients
 */
export interface IngredientsRequestBuilder extends BaseRequestBuilder<IngredientsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.ingredients.item collection
     * @param id Unique identifier of the item
     * @returns {IngredientsItemRequestBuilder}
     */
     byId(id: Guid) : IngredientsItemRequestBuilder;
    /**
     * Get all ingredients
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Ingredient[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Ingredient[] | undefined>;
    /**
     * Create a new ingredient
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Ingredient>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: IngredientRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Ingredient | undefined>;
    /**
     * Get all ingredients
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new ingredient
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: IngredientRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const IngredientsRequestBuilderUriTemplate = "{+baseurl}/api/ingredients";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IngredientsRequestBuilderNavigationMetadata: Record<Exclude<keyof IngredientsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: IngredientsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const IngredientsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: IngredientsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createIngredientFromDiscriminatorValue,
    },
    post: {
        uriTemplate: IngredientsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createIngredientFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeIngredientRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
