/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadgeResponseFromDiscriminatorValue, type BadgeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/badges
 */
export interface BadgesRequestBuilder extends BaseRequestBuilder<BadgesRequestBuilder> {
    /**
     * Get the badges of the currently authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BadgeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BadgeResponse[] | undefined>;
    /**
     * Get the badges of the currently authenticated user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BadgesRequestBuilderUriTemplate = "{+baseurl}/api/user/badges";
/**
 * Metadata for all the requests in the request builder.
 */
export const BadgesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BadgesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBadgeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
