/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createIngredientFromDiscriminatorValue, serializeIngredient, serializeIngredientRequest, type HttpValidationProblemDetails, type Ingredient, type IngredientRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ingredients/{id}
 */
export interface IngredientsItemRequestBuilder extends BaseRequestBuilder<IngredientsItemRequestBuilder> {
    /**
     * Delete an existing ingredient
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get an ingredient by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Ingredient>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Ingredient | undefined>;
    /**
     * Update an existing ingredient
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Ingredient>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: IngredientRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Ingredient | undefined>;
    /**
     * Delete an existing ingredient
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get an ingredient by id
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update an existing ingredient
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: IngredientRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const IngredientsItemRequestBuilderUriTemplate = "{+baseurl}/api/ingredients/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const IngredientsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: IngredientsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: IngredientsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createIngredientFromDiscriminatorValue,
    },
    put: {
        uriTemplate: IngredientsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createIngredientFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeIngredientRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
