/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createRecipeDetailResponseFromDiscriminatorValue, createRecipeResponseFromDiscriminatorValue, serializeCreateRecipeRequest, serializeRecipeResponse, type CreateRecipeRequest, type HttpValidationProblemDetails, type RecipeDetailResponse, type RecipeResponse } from '../../../models/index.js';
// @ts-ignore
import { FavoriteRequestBuilderRequestsMetadata, type FavoriteRequestBuilder } from './favorite/index.js';
// @ts-ignore
import { ImageRequestBuilderRequestsMetadata, type ImageRequestBuilder } from './image/index.js';
// @ts-ignore
import { PublishRequestBuilderRequestsMetadata, type PublishRequestBuilder } from './publish/index.js';
// @ts-ignore
import { RateRequestBuilderRequestsMetadata, type RateRequestBuilder } from './rate/index.js';
// @ts-ignore
import { type UnpublishRequestBuilder, UnpublishRequestBuilderRequestsMetadata } from './unpublish/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}
 */
export interface RecipesItemRequestBuilder extends BaseRequestBuilder<RecipesItemRequestBuilder> {
    /**
     * The favorite property
     */
    get favorite(): FavoriteRequestBuilder;
    /**
     * The image property
     */
    get image(): ImageRequestBuilder;
    /**
     * The publish property
     */
    get publish(): PublishRequestBuilder;
    /**
     * The rate property
     */
    get rate(): RateRequestBuilder;
    /**
     * The unpublish property
     */
    get unpublish(): UnpublishRequestBuilder;
    /**
     * Delete a recipe
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get a recipe by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeDetailResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeDetailResponse | undefined>;
    /**
     * Update an existing recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeResponse | undefined>;
    /**
     * Delete a recipe
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get a recipe by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update an existing recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RecipesItemRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecipesItemRequestBuilderNavigationMetadata: Record<Exclude<keyof RecipesItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    favorite: {
        requestsMetadata: FavoriteRequestBuilderRequestsMetadata,
    },
    image: {
        requestsMetadata: ImageRequestBuilderRequestsMetadata,
    },
    publish: {
        requestsMetadata: PublishRequestBuilderRequestsMetadata,
    },
    rate: {
        requestsMetadata: RateRequestBuilderRequestsMetadata,
    },
    unpublish: {
        requestsMetadata: UnpublishRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecipesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeDetailResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateRecipeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
