/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecipeResponseFromDiscriminatorValue, type RecipeResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}/unpublish
 */
export interface UnpublishRequestBuilder extends BaseRequestBuilder<UnpublishRequestBuilder> {
    /**
     * Unpublish a recipe (change from published to draft)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeResponse | undefined>;
    /**
     * Unpublish a recipe (change from published to draft)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UnpublishRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}/unpublish";
/**
 * Metadata for all the requests in the request builder.
 */
export const UnpublishRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UnpublishRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
