using dishes.Server.Data.Entities;
using Xunit;

namespace dishes.Server.Tests.Features.Identity;

public class AppIdentityUserUnitTests
{
    [Fact]
    public void AppIdentityUser_DefaultConstructor_InitializesProfileFields()
    {
        // Act
        var user = new AppIdentityUser();

        // Assert
        Assert.Equal(string.Empty, user.FullName);
        Assert.Equal(string.Empty, user.CulinaryTitle);
        Assert.Equal(string.Empty, user.Biography);
        Assert.Equal(string.Empty, user.Location);
        Assert.Equal(string.Empty, user.ProfilePhotoUrl);
        Assert.NotEqual(default, user.CreatedAt);
    }

    [Fact]
    public void AppIdentityUser_ConstructorWithUserName_InitializesProfileFields()
    {
        // Act
        var user = new AppIdentityUser("testuser");

        // Assert
        Assert.Equal("testuser", user.UserName);
        Assert.Equal(string.Empty, user.FullName);
        Assert.Equal(string.Empty, user.CulinaryTitle);
        Assert.Equal(string.Empty, user.Biography);
        Assert.Equal(string.Empty, user.Location);
        Assert.Equal(string.Empty, user.ProfilePhotoUrl);
        Assert.NotEqual(default, user.CreatedAt);
    }

    [Fact]
    public void AppIdentityUser_CreatedAtIsUtcNow()
    {
        // Act
        var beforeCreation = DateTime.UtcNow;
        var user = new AppIdentityUser();
        var afterCreation = DateTime.UtcNow;

        // Assert
        Assert.True(user.CreatedAt >= beforeCreation);
        Assert.True(user.CreatedAt <= afterCreation);
        Assert.Equal(DateTimeKind.Utc, user.CreatedAt.Kind);
    }

    [Fact]
    public void AppIdentityUser_CanSetProfileFields()
    {
        // Arrange
        var user = new AppIdentityUser("jdoe")
        {
            Email = "john@example.com"
        };

        // Act
        user.FullName = "John Doe";
        user.CulinaryTitle = "Head Chef";
        user.Biography = "Experienced chef with 10 years of experience";
        user.Location = "Paris, France";
        user.ProfilePhotoUrl = "https://example.com/john.jpg";

        // Assert
        Assert.Equal("John Doe", user.FullName);
        Assert.Equal("Head Chef", user.CulinaryTitle);
        Assert.Equal("Experienced chef with 10 years of experience", user.Biography);
        Assert.Equal("Paris, France", user.Location);
        Assert.Equal("https://example.com/john.jpg", user.ProfilePhotoUrl);
    }

    [Fact]
    public void AppIdentityUser_InheritsFromIdentityUser()
    {
        // Arrange & Act
        var user = new AppIdentityUser("testuser")
        {
            Email = "test@example.com",
            EmailConfirmed = true,
            PhoneNumber = "+1234567890",
            PhoneNumberConfirmed = false,
            TwoFactorEnabled = false,
            LockoutEnabled = true
        };

        // Assert
        Assert.Equal("testuser", user.UserName);
        Assert.Equal("test@example.com", user.Email);
        Assert.True(user.EmailConfirmed);
        Assert.Equal("+1234567890", user.PhoneNumber);
        Assert.False(user.PhoneNumberConfirmed);
        Assert.False(user.TwoFactorEnabled);
        Assert.True(user.LockoutEnabled);
    }

    [Fact]
    public void AppIdentityUser_HasUniqueId()
    {
        // Act
        var user1 = new AppIdentityUser();
        var user2 = new AppIdentityUser();

        // Assert - Both should have IDs generated by Identity system
        Assert.NotNull(user1.Id);
        Assert.NotNull(user2.Id);
        // Note: IDs are generated on database insert, these initial ones may be null initially
    }

    [Fact]
    public void AppIdentityUser_AllowsNullEmail()
    {
        // Act
        var user = new AppIdentityUser("testuser")
        {
            Email = null
        };

        // Assert
        Assert.Null(user.Email);
    }

    [Fact]
    public void AppIdentityUser_AllowsEmptyProfileFields()
    {
        // Act
        var user = new AppIdentityUser("testuser");

        // Assert - All profile fields should be empty strings by default
        Assert.Equal(string.Empty, user.FullName);
        Assert.Equal(string.Empty, user.CulinaryTitle);
        Assert.Equal(string.Empty, user.Biography);
        Assert.Equal(string.Empty, user.Location);
        Assert.Equal(string.Empty, user.ProfilePhotoUrl);
    }

    [Fact]
    public void AppIdentityUser_SupportsMaxLengthProfileData()
    {
        // Arrange
        var user = new AppIdentityUser("testuser");

        // Act - Set maximum realistic lengths
        user.FullName = new string('A', 255);
        user.CulinaryTitle = new string('B', 100);
        user.Biography = new string('C', 1000);
        user.Location = new string('D', 200);
        user.ProfilePhotoUrl = "https://example.com/" + new string('E', 450);  // Close to 500

        // Assert
        Assert.Equal(255, user.FullName.Length);
        Assert.Equal(100, user.CulinaryTitle.Length);
        Assert.Equal(1000, user.Biography.Length);
        Assert.Equal(200, user.Location.Length);
        Assert.True(user.ProfilePhotoUrl.Length >= 450);
    }

    [Fact]
    public void AppIdentityUser_CopyConstructor_PreservesUserName()
    {
        // Arrange
        string userName = "existinguser";

        // Act
        var user = new AppIdentityUser(userName);

        // Assert
        Assert.Equal(userName, user.UserName);
    }
}
