/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createImageUploadResponseFromDiscriminatorValue, serializeImageUploadResponse, serializeKeyValuePairOfstringAndStringValues, type ImageUploadResponse, type KeyValuePairOfstringAndStringValues } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}/image
 */
export interface ImageRequestBuilder extends BaseRequestBuilder<ImageRequestBuilder> {
    /**
     * Upload a cover image for a recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ImageUploadResponse>}
     */
     post(body: KeyValuePairOfstringAndStringValues[], requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ImageUploadResponse | undefined>;
    /**
     * Upload a cover image for a recipe
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: KeyValuePairOfstringAndStringValues[], requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ImageRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}/image";
/**
 * Metadata for all the requests in the request builder.
 */
export const ImageRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ImageRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createImageUploadResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeKeyValuePairOfstringAndStringValues,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
