/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFollowUserResponseFromDiscriminatorValue, type FollowUserResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/follows/{userId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * Unfollow a creator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Follow another creator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FollowUserResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FollowUserResponse | undefined>;
    /**
     * Unfollow a creator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Follow another creator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/api/user/follows/{userId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithUserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithUserItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    post: {
        uriTemplate: WithUserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFollowUserResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
