/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDishFromDiscriminatorValue, type Dish } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/dishes
 */
export interface DishesRequestBuilder extends BaseRequestBuilder<DishesRequestBuilder> {
    /**
     * Get all dishes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Dish[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Dish[] | undefined>;
    /**
     * Get all dishes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DishesRequestBuilderUriTemplate = "{+baseurl}/api/dishes";
/**
 * Metadata for all the requests in the request builder.
 */
export const DishesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DishesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDishFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
