/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/follows
 */
export interface FollowsRequestBuilder extends BaseRequestBuilder<FollowsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.user.follows.item collection
     * @param userId Unique identifier of the item
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FollowsRequestBuilderUriTemplate = "{+baseurl}/api/user/follows";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FollowsRequestBuilderNavigationMetadata: Record<Exclude<keyof FollowsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/* tslint:enable */
/* eslint-enable */
