/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecipeResponseFromDiscriminatorValue, type RecipeResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/published
 */
export interface PublishedRequestBuilder extends BaseRequestBuilder<PublishedRequestBuilder> {
    /**
     * Get all published recipes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeResponse[] | undefined>;
    /**
     * Get all published recipes
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PublishedRequestBuilderUriTemplate = "{+baseurl}/api/recipes/published";
/**
 * Metadata for all the requests in the request builder.
 */
export const PublishedRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PublishedRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createRecipeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
